name: Feature Request
description: Suggest a new feature
title: "[FEATURE] "
labels: ["type:feature", "status:todo"]
body:
  - type: markdown
    attributes:
      value: "Help us understand the value and scope."

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: "A short summary of the feature"
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this important? What problem does it solve?
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      placeholder: "- Given/When/Then ...\n- UX states ..."
